### ISSUE TITLE
importing font files of micro application to main application

### ISSUE THREAD

**Issue by HarithaRavee1** [single-spa/single-spa-react#113]
Hi, In the micro service application, if we create icon font files (.eot, .svg, .ttf and .woff), I will get the build file of this font files separately. So along with the build js file of the micro service, i will have to import the font files also to the main application. Is there a way to import such assets files from micro services while registering ?
![build files](https://user-images.githubusercontent.com/84369484/121509903-bb8a1200-ca04-11eb-8003-5a713b5a9b96.png)

**Comment by joeldenning** [comment]
Hi @HarithaRavee1, usually font files are loaded via CSS files. For example, in your CSS file:

```css
/* main.css */
@font-face {
  font-family: "Soehne";
  src: url("./font/soehne/soehne-web-fett.woff2") format("woff2"),
    url("./font/soehne/soehne-web-fett.woff") format("woff");
  font-weight: 800;
}
```

The CSS file should then be imported in your javascript code, or via webpack configuration:

```js
import './main.css';
```

Then in your webpack configuration, use `css-loader`. This tells webpack to process all `url()` statements in your CSS files. This is usually already present in most webpack configurations. See https://www.npmjs.com/package/css-loader.

You'll also need to tell webpack how to handle eot/ttf/woff files. In webpack 5, use `asset/resource` (see https://webpack.js.org/guides/asset-management/#loading-fonts).

Finally, you'll need to tell webpack the base url to load all the fonts from. This is done via [webpack public path](https://webpack.js.org/guides/public-path). If using SystemJS, you'll need to set the public path at runtime rather than at build time. To do so, use https://github.com/joeldenning/systemjs-webpack-interop. To diagnose the public path, add `console.log('public path', __webpack_public_path__)` to any javascript file in your project. In the browser console, you should see `public path http://localhost:8080` or similar. An empty string is not a correct public path when using SystemJS.
